name: Calculations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      -name: checkout code
      uses: actions/checkout@v6

      -name: setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14.0'

      -name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      -name: run flakes8
      run: flakes8 calculator.py

test: 
  runs-on: ubuntu-latest
  needs: lint

  steps:
  -name: checkout code
  uses: actions/checkout@v6

  -name: stepup python
  uses: actions/setup-python@v6
  with:
    python-version: '-8.8.2'

  -name: install dependencies
  run: pip install -r requirements.txt

  -name: run tests
  run: pytest testCalculator.py




